### PR TITLE
Cross references with DocumenterInterLinks

### LINKED ISSUE #32: Cross references to Trixi.jl
As mentioned in the comment below, we might need to fix the cross references to Trixi.jl:
```suggestion
- [`AnalysisCallback`](@ref) analyzes this variable.
+ [`AnalysisCallback`](https://trixi-framework.github.io/Trixi.jl/stable/reference-trixi/#Trixi.AnalysisCallback)
analyzes this variable.
```
I do not think that we can cross reference via `@ref` because this function info is in the Trixi docs. Thus, I think we need a direct link, or am I wrong @sloede ?

_Originally posted by @andrewwinters5000 in https://github.com/trixi-framework/TrixiShallowWater.jl/pull/30#discussion_r1539112292_

### PR DESCRIPTION
**Pull request by patrickersing**
This PR introduces [DocumenterInterLinks.jl](https://github.com/JuliaDocs/DocumenterInterLinks.jl) to handle external references to `Trixi.jl` in the docs and should fix #32.

### CODE REVIEW

File: src/equations/shallow_water_multilayer_1d.jl [hunk 1]
```diff
@@ -316,7 +315,7 @@ When the bottom topography is nonzero this scheme will be well-balanced when use
 nonconservative [`flux_nonconservative_ersing_etal`](@ref).
 
 To obtain an entropy stable formulation the `surface_flux` can be set as
-[`FluxPlusDissipation(flux_ersing_etal, DissipationLocalLaxFriedrichs()), flux_nonconservative_ersing_etal`](@ref).
```
Comment (andrewwinters5000) [inline src/equations/shallow_water_multilayer_1d.jl:319]: Did this ref get removed because there are versions of, e.g., `flux_ersing_etal` in Trixi and TrixiSW?

**Review by andrewwinters5000 — CHANGES_REQUESTED** [review]
LGTM! I just left one question. It was nice that this was easy to setup. Thanks for the suggestion @sloede

File: src/equations/shallow_water_multilayer_1d.jl (hunk 1 above)
Comment (patrickersing) [reply src/equations/shallow_water_multilayer_1d.jl:319]: I did not manage to resolve the links correctly with the function arguments, so I removed the reference.

Comment (andrewwinters5000) [reply src/equations/shallow_water_multilayer_1d.jl:319]: That makes sense, the `@ref` probably gets confused with which function it should jump to between the four available within the tick marks.

**Review by andrewwinters5000 — APPROVED** [review]
